ALTER TABLE "projects"
  ADD COLUMN IF NOT EXISTS "serviceName" TEXT,
  ADD COLUMN IF NOT EXISTS "unitName" TEXT,
  ADD COLUMN IF NOT EXISTS "unitCount" INTEGER,
  ADD COLUMN IF NOT EXISTS "unitPrice" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "costPerUnit" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "subtotalAmount" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "gstPercent" DOUBLE PRECISION NOT NULL DEFAULT 18,
  ADD COLUMN IF NOT EXISTS "gstAmount" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "finalAmount" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "profitAmount" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "invoicingPolicy" TEXT,
  ADD COLUMN IF NOT EXISTS "tags" TEXT,
  ADD COLUMN IF NOT EXISTS "expectedClosingDate" TIMESTAMP(3);
